### ISSUE TITLE
Javadocs?

### ISSUE THREAD

**Issue by abevoelker** [ymasory/iText-4.2.0#1]
Hello, very useful repo you have here!  Thank you for archiving this important library.

One thing that would be a good complement to it is the Javadoc documentation, as the iText site only has documentation related to the newer version of iText (unless I'm missing something?).

There is an ant task that can be ran to create the Javadocs (`ant javadoc`), which I've used to put up on my own website for now: http://itext-docs.abevoelker.com/

However, I was thinking this is probably a common concern for people using this library.  Perhaps you could use GitHub Pages to host these Javadocs at http://ymasory.github.com/iText-4.2.0 ?  Just an idea.

**Comment by abevoelker** [comment]
Hi, I created a `gh-pages` branch [here](https://github.com/ccap/iText-4.2.0/tree/gh-pages).  I would have liked to send a pull request but apparently GitHub doesn't allow creating pull requests that create new upstream branches.  In other words, since you don't have an existing `gh-pages` branch I couldn't send you a nice clean pull request.

So instead, you can do this:

```
git remote add ccap git://github.com/ccap/iText-4.2.0.git
git remote update
git checkout -b gh-pages
git reset --hard ccap/gh-pages
git push origin gh-pages
```

**Comment by ymasory** [comment]
Sure good idea. I'll try to do this today. Thanks!

**Comment by ymasory** [comment]
(On a similar note I've been meaning to deploy the artifacts to maven central under com.yuvimasory, to round things out.)

**Comment by ymasory** [comment]
There it is: http://ymasory.github.com/iText-4.2.0/
Linked to on the readme too.

**Comment by abevoelker** [comment]
Thank you!
